/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed': '#002020',
        'on-secondary-fixed-variant': '#38485d',
        'on-primary': '#002388',
        'on-primary-container': '#c3ccff',
        tertiary: '#2ddbde',
        'tertiary-container': '#006264',
        'on-error-container': '#ffdad6',
        'primary-fixed-dim': '#b8c3ff',
        'surface-variant': '#323537',
        'primary-fixed': '#dde1ff',
        'on-primary-fixed': '#001356',
        'primary-container': '#0042e7',
        'surface-tint': '#b8c3ff',
        'surface-container': '#1d2022',
        'surface-container-low': '#191c1e',
        'tertiary-fixed-dim': '#2ddbde',
        surface: '#101415',
        'inverse-surface': '#e0e3e5',
        'error-container': '#93000a',
        'surface-dim': '#101415',
        'on-error': '#690005',
        'outline-variant': '#434653',
        'on-secondary': '#213145',
        'on-tertiary-container': '#3ce3e6',
        'surface-container-lowest': '#0b0f10',
        'surface-bright': '#363a3b',
        'on-primary-fixed-variant': '#0035be',
        'secondary-container': '#3a4a5f',
        'secondary-fixed': '#d3e4fe',
        'on-surface': '#e0e3e5',
        secondary: '#b7c8e1',
        'secondary-fixed-dim': '#b7c8e1',
        'inverse-primary': '#124af0',
        'inverse-on-surface': '#2d3133',
        outline: '#8d909e',
        'tertiary-fixed': '#5af8fb',
        'on-secondary-fixed': '#0b1c30',
        'on-surface-variant': '#c3c6d5',
        'on-secondary-container': '#a9bad3',
        background: '#101415',
        primary: '#b8c3ff',
        error: '#ffb4ab',
        'on-tertiary': '#003738',
        'on-background': '#e0e3e5',
        'on-tertiary-fixed-variant': '#004f51',
        'surface-container-high': '#272a2c',
        'surface-container-highest': '#323537',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        display: ['Manrope', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
